default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bulk_mail_mvp_development
  username: postgres
  password: <%= ENV.fetch("PGPASSWORD", "") %>
  host: localhost

test:
  <<: *default
  database: bulk_mail_mvp_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
